### ISSUE TITLE
Package issue while loading

### ISSUE THREAD

**Issue by priyamshah112** [lispgames/perfectstorm#4]
![image](https://user-images.githubusercontent.com/25688111/55580360-02e72a80-5738-11e9-9b28-6f27b20cf4ae.png)

I am new to lisp, please help me out with this.

**Comment by gpadd** [comment]
Most likely you need to install a glut implementation on your system. That's all I can deduce from the error message.
So it's more of a "I'm missing library" than a lisp problem.
I must warn you though, this project is nowhere near finished, and currently nobody is working on it.
BUT, if you talk to the others on the channel on Freenode, #lispgames you or others could possibly help out with moving the project forward.
That'd be awesome.

**Comment by priyamshah112** [comment]
Ty! I installed glut separately and it worked!
